name: Publish package to GitHub Packages
on:
  push:
    tags:
      - '2.*'
      - '3.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'maven'

      - name: Force version
        run: mvn --no-transfer-progress --batch-mode versions:set -DnewVersion=${{github.ref_name}}
      - name: Publish package
        run: mvn --no-transfer-progress --batch-mode deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/${{github.repository}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}